[package]
name = "build_tools"
version = "0.1.0"
authors = ["gaeksoul@gmail.com <gaeksoul@gmail.com>"]

[dependencies]
hotwatch = "0.3.1"
parking_lot = "0.6.2"
sass-rs = "0.2.1"
derive_more = "0.11.0"
